from __future__ import annotations
from dataclasses import dataclass
from enum import IntFlag, auto
from typing import Iterable, Protocol, TypeAlias, overload

from typing_extensions import Self

from pybind11_stubgen import structs

Identifier = structs.Identifier
Import = structs.Import
Module = structs.Module
ResolvedType = structs.ResolvedType
QualifiedName = structs.QualifiedName

NamespaceDict: TypeAlias = dict[Identifier, tuple["ModuleWrapper", "GetNamesRules"]]


class GetNamesRules(IntFlag):
    NONE = 0
    ATTRIBUTES = auto()
    CLASSES = auto()
    FUNCTIONS = auto()
    TYPE_VARS = auto()
    RE_EXPORT_ALT_IMPORTS = auto()
    MODULE = auto()


@dataclass
class ImportAlt(Protocol):
    module: ModuleWrapper
    filter_rules: GetNamesRules | None = None
    filter_names: list[Identifier] | None = None
    import_all: bool = False
    import_module: bool = False

    def get_imported_namespace(self) -> NamespaceDict: ...
    def to_pybind11_import(self, import_from: ModuleWrapper) -> Import: ...


@dataclass
class TypeInStr:
    name: str
    params: list[TypeInStr] | None = None


class TypeResolver(Protocol):
    imports: set[structs.Import]
    pending: list[tuple[str, QualifiedName]]

    def fix(self, type_name: str, fixed: QualifiedName): ...
    def from_str(self, type_name: str) -> ResolvedType: ...
    def from_value(self, value: TypeInStr) -> ResolvedType: ...


class ModulePath(Protocol):
    @overload
    def __getitem__(self, key: slice) -> Self: ...
    @overload
    def __getitem__(self, key: int) -> Identifier: ...
    def __getitem__(self, key) -> Self | Identifier: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...

    @classmethod
    def root(cls, iterable: Iterable[Identifier]) -> Self: ...
    def imports(
        self, *, names: Iterable[Identifier] | None = None, all: bool = False
    ) -> Import: ...
    def is_absolute(self) -> bool: ...
    def is_relative(self) -> bool: ...


class ModuleTree(Protocol):
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def is_file(self) -> bool: ...
    @property
    def children(self) -> list[ModuleTree]: ...
    @property
    def parent(self) -> ModuleTree | None: ...
    def append_child(self, child: ModuleTree): ...
    def remove_child(self, child: ModuleTree): ...
    def abs(self) -> ModulePath: ...
    def root(self) -> ModuleTree: ...
    def relative(self, other: ModuleTree) -> ModulePath: ...
    def resolve(self, path: ModulePath) -> ModuleTree: ...


class ModuleRegister(Protocol):
    def __init__(self, name: str) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def add(self, module: ModuleWrapper) -> ModuleWrapper: ...
    def append_child(self, parent: ModuleWrapper, child: ModuleWrapper): ...
    def get_by_abs(self, abs: ModulePath) -> ModuleWrapper: ...
    def get_by_tree(self, tree: ModuleTree) -> ModuleWrapper: ...
    def get_children(self, parent: ModuleWrapper) -> set[ModuleWrapper]: ...


class ModuleWrapper(Protocol):
    def __init__(
        self,
        module: Module,
        resolver: TypeResolver,
        register: ModuleRegister,
        imports: list[ImportAlt] | None = None,
        exports_rules_negative: GetNamesRules = GetNamesRules.NONE,
    ): ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def module(self) -> Module: ...
    @property
    def resolver(self) -> TypeResolver: ...
    @property
    def tree(self) -> ModuleTree: ...
    @property
    def children(self) -> set[ModuleWrapper]: ...
    def append_child(self, child: ModuleWrapper): ...
    def exports(
        self, rules_overwrite: GetNamesRules | None = None
    ) -> NamespaceDict: ...
    def fix_unresolved(
        self, name: QualifiedName
    ) -> tuple[Import | None, Identifier] | None: ...
    def bake_module(self) -> Module: ...
