from __future__ import annotations
from enum import IntFlag, auto
from typing import Iterable, Protocol, overload

from typing_extensions import Self

from pybind11_stubgen import structs

Identifier = structs.Identifier
Import = structs.Import


class ModulePath(Protocol):
    @overload
    def __getitem__(self, key: slice) -> Self: ...
    @overload
    def __getitem__(self, key: int) -> Identifier: ...
    def __getitem__(self, key) -> Self | Identifier: ...
    def __str__(self) -> str: ...

    @classmethod
    def root(cls, iterable: Iterable[Identifier]) -> Self: ...
    def imports(
        self, *, names: Iterable[Identifier] | None = None, all: bool = False
    ) -> Import: ...
    def is_absolute(self) -> bool: ...
    def is_relative(self) -> bool: ...


class ModuleTree(Protocol):
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def append_child(self, child: ModuleTree): ...
    def remove_child(self, child: ModuleTree): ...
    def abs(self) -> ModulePath: ...
    def root(self) -> ModuleTree: ...
    def relative(self, other: ModuleTree) -> ModulePath: ...


class GetNamesRules(IntFlag):
    NONE = 0
    ATTRIBUTES = auto()
    CLASSES = auto()
    FUNCTIONS = auto()
    TYPE_VARS = auto()
    RE_EXPORT_ALT_IMPORTS = auto()
    MODULE = auto()
