from typing import Generic, Iterable, TypeVar

T = TypeVar("T")

class vector_of(Generic[T]):
    def extend(self, _: Iterable[T]) -> None: ...
    def append(self, _: int) -> None: ...
    def __str__(self) -> str: ...
